<?php
/**
 * Mage Utility
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the MIT License (MIT)
 * that is bundled with this package in the file LICENSE_MIT.txt.
 * It is also available through the world-wide-web at this URL:
 * https://opensource.org/licenses/MIT
 *
 * @copyright   Copyright (c) 2016 Shaughn Le Grange - Hatlen (http://shaughn.pro)
 * @license     https://opensource.org/licenses/MIT  MIT License (MIT)
 */

namespace MageUtility;

use MageUtility\Console\Command\InstallMagentoCommand;
use Symfony\Component\Console\Application;
use Symfony\Component\Console\Tester\CommandTester;

class MageUtilityTest extends \PHPUnit_Framework_TestCase
{
    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    public function tearDown()
    {
        parent::tearDown(); // TODO: Change the autogenerated stub
    }

    /**
     * Test install Magento execute returns complete
     */
    public function testInstallMagentoExecute()
    {
        $application = new Application();
        $application->add(new InstallMagentoCommand());

        $command = $application->find('install-magento');
        $commandTester = new CommandTester($command);

        $commandTester->execute(array(
            'command'      => $command->getName(),
            '--name'         => 'TestProject'
        ));

        $this->assertRegexp('/Complete/', $commandTester->getDisplay());
        //$this->assertRegExp('/.../', $commandTester->getDisplay());
    }
}